### ISSUE TITLE
FrameStack Issue

### ISSUE THREAD

**Issue by right-chan** [N1-314/Intrinsic-Curiosity-Module---PyTorch#5]
`gym/wrappers/frame_stack.py `의 `class FrameStack(gym.ObservationWrapper)`에서

```python
def step(self, action):
    ...
    self.frames.append(observation)
    ...
```
을
```python
def step(self, action):
    ...
    self.frames.append(observation.copy())
    ...
```
으로 바꾸는 것이 맞는건가요?

![image](https://github.com/N1-314/Intrinsic-Curiosity-Module---PyTorch/assets/83287616/d886603e-f7c7-4ab8-954f-342280e74be8)
![image](https://github.com/N1-314/Intrinsic-Curiosity-Module---PyTorch/assets/83287616/ba76eae3-6744-437e-9fde-9b77fe9af5f2)

**Comment by HyeAnn-Lee** [comment]
lazyframe 풀어서 frame별로 비교하다가 발견하신거죠? 저도 화면이 계속 같게 나와서 뭔가 했는데.. .copy()를 적용한 결과를 보면 .copy()해봐야하나 싶다가도
- 이거에 관한 기존의 불평불만이 없음
- 이름이 "lazy"임

이라는 이유를 생각해보면 author들이 의도한 동작이 맞지 않을까요?
copy를 매번 하면 메모리가 어떻게 될지도 잘 모르는거고, lazy한 어떤 operation이 어디선가 잘 되고 있는 것이 아닐까요?

디버깅용으로는 copy() 붙여서 사용해도 괜찮을 것 같지만, 실제 코드 돌릴때는 원래대로 돌리는 게 맞다고 생각합니다 (근거없음)

**Comment by HyeAnn-Lee** [comment]
=> Discussion #7 
이제 해결된걸까요..? ㅇㅅㅇ

**Comment by right-chan** [comment]
넵, 해결되었습니다.
